wget https://raw.githubusercontent.com/ly-temp/my_bash/main/crawler_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/downloader_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/scan_html_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/downloader_pausable_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/web3storage_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/web3storage_syncfolder_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/ssh_ping_LY.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/lock_crawler.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/fileio_syncfolder.sh
wget https://raw.githubusercontent.com/ly-temp/my_bash/main/fileio.sh
